"""Generate the Dart catalog from the reviewed multilingual JSON catalog."""
import json,pathlib
catalog = json.loads(pathlib.Path('lib/l10n/catalog.json').read_text(encoding='utf-8'))
def literal(value): return json.dumps(value,ensure_ascii=False).replace('$',r'\$')
lines = ['// Generated by tool/generate_localizations.py. Edit catalog.json instead.', 'const translations = <String, List<String>>{']
for key, values in catalog.items():
    assert len(values)==2 and all(values), key
    lines.append(f'  {literal(key)}: [{literal(values[0])}, {literal(values[1])}],')
lines.append('};')
lines.append('const sourceTranslations = <String, String>{')
for key,value in json.loads(pathlib.Path('lib/l10n/catalog_kk.json').read_text(encoding='utf-8')).items():
    lines.append(f'  {literal(key)}: {literal(value)},')
lines.append('};')
pathlib.Path('lib/l10n/translations.dart').write_text('\n'.join(lines)+'\n',encoding='utf-8')
print(f'Generated {len(catalog)} translation pairs.')
